version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledge
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'

  celery:
    build:
      context: ./backend
    command: celery -A app.tasks.send_reminders.celery_app worker --beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db_data:
